### ISSUE TITLE
DS3 Controller throws an error at shibari from airbender

### ISSUE THREAD

**Issue by megadrago88** [ViGEm/AirBender#4]
After setting up fireshock V2, Then Airbender Then Shibari (FYI Had to do ALOT of scouting for how to install properly on discord, forums, etc.) It gave me the all clear but after disconnecting my two DS3 controllers it spouted errors constantly at me even after removing the BT dongle. Attached is my log file.
[Shibari.Dom.Server-20180209.log](https://github.com/nefarius/AirBender/files/1712856/Shibari.Dom.Server-20180209.log)

**Comment by megadrago88** [comment]
I'm putting this here as It only seems to originate from airbender, but I'm trying to debug it further.

**Comment by nefarius** [comment]
That's a know bug (see #5).

I know the docs are lacking; that's because the projects aren't considered release-ready.
